### ISSUE TITLE
Missing sound database for downloads

### ISSUE THREAD

**Issue by chris-hld** [TWOEARS/Auditory-Machine-Learning-Training-and-Testing-Pipeline#46]
`https://dev.qu.tu-berlin.de/projects/twoears-getdata/repository/raw/sound_databases/`

does not contain the sounds needed for test scrips. (e.g. folder `/generalSoundsNI/...`).

**Comment by kashefy** [comment]
@chris-hld, this is true, we are not permitted to upload the raw sound files from this database.

**Comment by kashefy** [comment]
@ivo--t, should we update the test scripts to use the IEEE_AASP flists?

**Comment by chris-hld** [comment]
Maybe its better to provide a meaningful warning/error message instead?

**Comment by kashefy** [comment]
What does it currently do? "Failed to download..."?

**Comment by kashefy** [comment]
@chris-hld, can you also tell us which script you were trying to run?

**Comment by chris-hld** [comment]
I just tried some randomly. E.g. `run test/buildAndStoreCleanMulticlassData.m`
Yep, there is the warning from `downloadFile.m`:
> Warning: Download also failed with alternative database

and then immediately the error:

> Error using Core.IdentTrainPipeData/loadFileList (line 331)
> sound_databases/generalSoundsNI/alarm/AlarmElectronic+6061_43.wav, referenced in
> learned_models/IdentityKS/trainTestSets/NIGENS160807_mini_TrainSet_1.flist, not found!

**Comment by chris-hld** [comment]
I just wanted to indicate that it's not obvious for others that the reason for the error is not a download failure, but the URL pointing to a non-existing folder in the first place..

**Comment by kashefy** [comment]
Of course, a legitimate issue. I will update all the test scripts to point to data that is available on the public database. Let's keep this issue open until the test scripts are updated.
@ivo--t , this should happen today in time for the next release, so let's coordinate.

**Comment by hagenw** [comment]
@kashefy: don't worry the `test/` folder doesn't have to be included in the official release. You can focus first on the other stuff. Only if you insist to also include the `test/` folder, then this has to be fixed in time.

**Comment by kashefy** [comment]
I'm ok with omitting `test/`.
@ivo--t, what do you think?
