### ISSUE TITLE
nanmean and nanstd

### ISSUE THREAD

**Issue by hagenw** [TWOEARS/Auditory-Machine-Learning-Training-and-Testing-Pipeline#47]
In `src/+ModelTrainers/GlmNetLambdaSelectTrainer.m` the function `nanmean()` and `nanstd()` are used on line 92 and 93. Those are part of the statistics toolbox and so far we have avoided to use those functions.

`nanmean()` should be easily solveable as we have `nanMean()` in the balckboard system, see https://github.com/TWOEARS/blackboard-system/blob/master/src/tools/nanMean.m
For `nanstd()` we have to implement it.

It would be nice to have, otherwise the training demo (https://github.com/TWOEARS/examples/pull/14) will not run.

**Comment by ivo--t** [comment]
Done, added nanStd to Blackboard-System and changed GlmNetLambdaSelectTrainer accordingly.
